name: Build Package

on:
  push:
    branches:
      - main # Adjust this to your main branch
  pull_request:
    branches:
      - main # Adjust this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - name: Publish package (optional)
        run: npm publish --access public # Uncomment if you want to publish automatically
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use a secret for npm token
